yaito6502/minishell

includes/minishell.h

minishell.hを修正

---

includes/minishell.h

[update]ヘッダー更新

---

srcs/signal_handler.c

SIGINT,SIGQUITが発生した場合に呼ぶ関数をそれぞれ追加しました。
個別テスト用のmainをコメントアウトしてあります。main関数のnormは未対応です。

[add]シグナルハンドラーの追加

---

includes/minishell.h
srcs/tests/print_tcommand.c
srcs/tests/test_utils.c
srcs/utils/create_new_tcommand.c

初期値のt_commandを返す関数です。
テストコードをsrcs/testsに追加しています。

[add] create_new_tcommand()追加

---

Makefile
includes/minishell.h
srcs/execute/connect_pipeline.c
tests/execute/test_connect_pipeline.c

次コマンドへpipeを通して標準出力を送る関数、前コマンドのpipeから標準入力を受け取る関数を追加しました。+makefileファイル名修正

[add] connect_pipeline.c追加

---

Makefile
includes/minishell.h
srcs/execute/do_redirection.c
testinout/infile1
testinout/infile2
tests/execute/test_do_redirection.c

リダイレクトを行う関数を追加しました。
エラー処理は、プロセスで処理が変わるため、現在は暫定的な出力のみです。
テストも正常系のみになります。

[add] do_redirection.c追加

---

Makefile
srcs/main/main.c

仮のメイン関数追加、makefileでコンパイルできるようにmakefileを修正

[fix,add] Makefile修正

---

Makefile
includes/minishell.h
srcs/execute/get_cmd_frompath.c
tests/execute/test_get_cmd_frompath.c

[add] get_cmd_frompath()追加

---

Makefile
includes/minishell.h
srcs/execute/read_command.c
tests/execute/test_read_command.c

標準入力から受け取った文字列を格納する配列に蓋をする位置を変更したものの、pushし忘れていたのでその分の変更になります。

[fix] read_commandの修正

---

Makefile
includes/minishell.h
srcs/utils/add_str_to_list.c
tests/utils/test_add_str_to_list.c

[add] add_str_to_list()追加

---

Makefile
includes/minishell.h
srcs/execute/join_path.c
tests/execute/test_join_path.c

相対パスとカレントディレクトリから絶対パスを生成する関数を追加しました。makefileのTESTCOREの削除も併せて行っています。

[add, fix] join_path()追加

---

srcs/utils/add_newval_to_env.c

[fix] add_new_val_toenv()修正

---

Makefile
includes/minishell.h
srcs/builtin/execute_unset.c
tests/builtin/test_execute_unset.c

ビルトインコマンドのunsetを再現した関数を実装しました。
エラー時、コマンド終了時の処理は未実装です。

[add] execute_unset()追加

---

Makefile

冗長だったテストコマンドを修正しました。
その他、ファイルの重複などを修正しています。

[fix] Makefile修正

---

srcs/builtin/execute_env.c
srcs/builtin/execute_unset.c
srcs/execute/do_redirection.c
srcs/execute/execute_parallel.c
srcs/execute/execute_sequential.c
srcs/execute/get_cmd_frompath.c
srcs/execute/join_path.c
srcs/execute/start_commands.c
srcs/main/main.c
srcs/parser/parser_utils.c
srcs/utils/add_str_to_list.c

[fix] warning修正

---

Makefile
includes/minishell.h
srcs/builtin/execute_pwd.c
tests/builtin/test_execute_pwd.c

カレントディレクトリのパスを表示するbuiltin関数を実装しました。

[add] execute_pwd()追加

---

Makefile
includes/minishell.h
srcs/execute/store_exitstatus.c
tests/execute/test_store_exitstatus.c

[add] store_exitstatus()追加

---

Makefile
includes/minishell.h
srcs/history/history.c
tests/history/test_history.c

lineを保存する双方向リストhistoryを操作する関数群を追加しました。

[add] history.c追加

---

srcs/execute/reconnect_stdfd.c

norm改訂に向けてif文内での代入をしないよう修正しました。

[fix] reconnect_stdfd() 修正

---

Makefile
includes/minishell.h
srcs/parser/expand_envval.c
srcs/parser/expander.c
tests/parser/test_expand_envval.c
tests/parser/test_expander.c

環境変数展開する関数expand_envval()とcmd.argvに対して環境変数展開、クォート削除を行うpreprocess_command()を追加しました。

[add]環境変数展開、クォート削除追加

---

Makefile
includes/minishell.h
srcs/builtin/execute_unset.c
srcs/utils/validate_envkey.c
tests/builtin/test_execute_unset.c
tests/utils/test_validate_envkey.c

[fix] execute_unset()修正

---

srcs/tokenizer/tokenize.c
tests/tokenizer/test_tokenize.c

[fix]tokenizerリーク修正

---

srcs/utils/validate_envkey.c

[fix] validate_envkey修正

---

srcs/builtin/execute_env.c
tests/builtin/test_execute_env.c

[fix] execute_env修正

---

srcs/main/main.c
srcs/main/read_line.c

read_line中にCtrl-Dを入力したときの動作を改善しました。

[update]EOF 入力時動作改善

---

srcs/execute/error_redirect.c
tests/execute/test_do_redirection.c

[fix]エラー出力修正

---

Makefile
includes/minishell.h
srcs/tokenizer/validate_line.c
tests/tokenizer/test_validate_line.c

実装範囲外の不正なトークン、トークンの連続を検出するための関数を追加しました。

[add] validate_line追加

---

includes/minishell.h
srcs/builtin/execute_unset.c
srcs/execute/connect_pipeline.c
srcs/execute/error_execute.c
srcs/execute/execute_parallel.c
srcs/execute/start_commands.c
srcs/history/history.c
srcs/main/main.c
srcs/parser/expander.c

マージされた関数をすべて処理に組み込みました。
その他、デバッグ出力、未使用関数の削除など行っています。

[fix]main関数修正。その他軽微な調整

---

includes/minishell.h
srcs/utils/free_commandslist.c

[update]libft、free_commandlist修正

---

srcs/builtin/execute_builtin.c
srcs/builtin/execute_cd.c
srcs/builtin/execute_echo.c
srcs/builtin/execute_exit.c
srcs/builtin/execute_export.c
srcs/builtin/execute_pwd.c
srcs/builtin/execute_unset.c

[fix]builtinノーム対応

---

srcs/utils/create_new_tcommand.c
srcs/utils/create_newenv.c
srcs/utils/free_commandslist.c
srcs/utils/is_builtin.c
srcs/utils/print_sorted_env.c
srcs/utils/update_env.c

[fix]utils norm対応

---

srcs/history/display_history.c
srcs/history/history.c
srcs/history/update_history.c
srcs/tokenizer/tokenize.c
srcs/tokenizer/validate_line.c

[fix]history, tokenizer norm v3対応

---

Makefile
includes/minishell.h
srcs/execute/connect_pipeline.c
srcs/execute/do_redirection.c
srcs/execute/error_execute.c
srcs/execute/execute_parallel.c
srcs/execute/execute_sequential.c
srcs/execute/get_cmd_frompath.c
srcs/execute/join_path.c
tests/execute/test_get_cmd_frompath.c

[fix] コマンド実行部norm対応

---

Makefile
includes/minishell.h
srcs/execute/start_commands.c
srcs/expander/expand_envval.c
srcs/expander/expander.c
srcs/expander/validate_redirect.c
srcs/main/get_signal_in_execute.c
srcs/main/get_signal_in_read_line.c
srcs/main/main.c
srcs/main/read_line.c
srcs/main/termcap_setting.c
srcs/utils/print_sorted_env.c

print_sorted_env内でnorm対応したコードコンパイルエラー出るため元に戻しています。

[fix]main,expander norm v3対応

---

srcs/expander/expand_envval.c
srcs/tokenizer/tokenize.c
tests/expander/test_expander.c
tests/tokenizer/test_tokenize.c

echo "$ $"のように$の後にスペースが続くとき$を出力するよう変更しました。

[fix]$の後にスペースが続くとき$を出力するよう変更

---

srcs/builtin/execute_echo.c

[fix]不要な処理を削除

---

srcs/main/main.c
srcs/utils/print_sorted_env.c

minishell起動時にOLDPWDのvalueをnullで初期化するようにしました。
その他
print_sorted_envのバグとnorm修正
マージソートのスワップ条件の修正などを行いました。

OLDPWDの初期化処理追加

---

srcs/main/main.c
srcs/utils/create_newenv.c
srcs/utils/update_shlvl.c

起動後変数の初期化を行う関数を追加しました。
update_shlvl()でft_strtrimで確保したメモリをfreeするよう変更しました。

[add]初期化関数追加

---

srcs/execute/execute_parallel.c

[fix]コンパイルエラー解消

---

srcs/main/read_line.c

[fix]入力中にCtrl-\を入力した際の動作を改善。

---

srcs/history/get_cursor_position.c

[fix]get_cursor_position修正
