includes/minishell.h

printf関数が使用可能な為、stdio.hヘッダのインクルードを追加しました。

[update]　ヘッダーインクルードの追加 (#3)

---

Makefile
includes/minishell.h
srcs/utils/is_builtin.c
tests/utils/test_is_builtin.c

built-in判定用の関数追加しました。
あわせてmakefileのテストを変更し、make 実装関数名でテストできるようにしました。

[add,fix] is_builtin()追加、makefile更新

---

Makefile
includes/minishell.h
srcs/utils/create_newenv.c
tests/utils/test_create_newenv.c

environをheap領域にコピーする関数です。
ヘッダーファイル、makefileのコンフリクトが起きそうな部分をあらかじめ取り込んでいます。

[add]create_newenv()追加

---

srcs/utils/create_newenv.c
tests/utils/test_create_newenv.c

environの各文字列もheapにコピーするように変更しました。値の修正、メモリ開放を一貫した操作で行えるようになります。

[fix] create_newenv修正

---

Makefile
srcs/utils/add_newval_to_env.c
tests/utils/test_add_newval_to_env.c

テスト用に追加していたmerge済みのstatic関数を削除、libftのmakefile、libft.hにft_reallocを追加。makefileのテスト用コマンドからソースの重複を削除するように変更しました。現在のすべてのテストで動作確認済みです。

[fix] 不要関数削除、libft修正、makefile修正

---

srcs/utils/add_newval_to_env.c
tests/utils/test_add_newval_to_env.c

ft_spreallocの使用へ修正しました。
テストでメモリーリークがないことを確認しています。

[fix] fix_addnewvaltoenv()

---

srcs/parser/parser.c
srcs/parser/parser_utils.c
srcs/utils/add_str_to_list.c
tests/parser/test_parser.c

if文の中で代入を行わないようにしました。入力が不正な時にbashと同じエラー出力をするように変更しました。
また、全てのボーナスに対応させています。

いくつかのケースでbashと異なるエラーメッセージが出てしまうことを確認しています。
・";;;;"のように区切り文字が空白無しで連続している時
・"><><>"のようにリダイレクト文字が連続している時
・"| ; | ; |"のように別の区切り文字が交互に繰り返される時
いずれもtokenizerの実装を書き換え、パーサーに渡る文字列を変更する方が作業が簡単だと思いましので一旦マージできれば、と考えています。

[fix,update] normV3に備えたコードの修正、エラー出力機能追加

---

srcs/tokenizer/tokenize.c
tests/tokenizer/test_tokenize.c

クォート中に奇数個クォートが含まれているときの処理を修正しました。
修正前は"world's"のようなトークンを正しく認識できていませんでした。

[fix] tokenize() 修正

---

Makefile
includes/minishell.h
srcs/builtin/execute_builtin.c
srcs/execute/error_execute.c
srcs/execute/execute_parallel.c
srcs/execute/execute_sequential.c
srcs/execute/read_command.c
srcs/execute/start_commands.c
srcs/main/main.c
srcs/tokenizer/tokenize.c

コマンド実行時、PATHからコマンドが見つからなかったとき、実行ファイルが存在しないとき、実行権限がないときのエラー出力を追加しました。
加えてminishellがコンパイルできるようread_command()に一時的な修正をしています。

[fix]コマンド実行時エラー出力追加

---

srcs/parser/expand_envval.c
tests/builtin/test_execute_unset.c

expand_envval内のhas_doller()のnorm対応。また、preprocess_commandのエッジケースを発見しました。
had_doller()はコンパイルエラーを直した際にnormに遵守することを忘れていたため、書き換えました。
expand_unsetのエラー出力テストを行った際に、クオートのみの文字列が連続して続くと
エラー文が表示される回数が少なくbashとの差異が出てしまっていました。
bash
```
bash-3.2$ unset "" "" INVALID
bash: unset: `': not a valid identifier
bash: unset: `': not a valid identifier
```
minishell
```
bash-3.2$ ./test
bash: unset: `': not a valid identifier
```

[fix] expand_envvalのnorm対応、他。

---

srcs/tokenizer/tokenize.c

[fix] tokenizer修正

---

Makefile
includes/minishell.h
srcs/builtin/execute_export.c
srcs/utils/ft_str_sandwich.c
srcs/utils/print_sorted_env.c
srcs/utils/update_env.c
tests/builtin/test_execute_export.c
tests/builtin/test_execute_export.sh

tests/builtin/test_execute_export.shを使用してテストを行えます。
```
export
export [key]
export [key = value]
```
以上のパターンに対応しています。
メモリリークについては、update_env.c内で一件残っていますが詳しい原因は調査中です。

execute_export()追加

---

srcs/builtin/execute_exit.c
srcs/builtin/execute_unset.c
srcs/utils/add_str_to_list.c
srcs/utils/wrap_exit.c

execute_exitからexitする際、現在の実装で解放できるヒープを開放するよう変更しました。
併せてexecute_unsetのメモリリークを修正しています。

[add]wrap_exit追加、メモリリーク解消

---

includes/minishell.h
srcs/main/main.c
srcs/parser/parser_utils.c
srcs/tokenizer/validate_line.c
srcs/utils/add_str_to_list.c

ヘッダーのnorm対応、コンパイルエラー、add_str_to_listのエラーを修正しました。
ヘッダーのグローバル変数の命名は#100とこのプルリクが取り込まれてから変更します。

[fix]norm対応、コンパイルエラー修正など

---

includes/minishell.h
srcs/execute/error_execute.c
srcs/execute/execute_parallel.c
srcs/execute/execute_sequential.c

error_execute関数実行中にエラーが発生したときerrnoが変更され期待した動作ができていなかった問題を修正しました。
具体的には標準エラーがdev/nullにリダイレクトされていた時errnoが9になり、終了ステータスの設定がうまく行えていませんでした。

[fix]error_execute修正

---

Makefile
includes/minishell.h
srcs/builtin/execute_unset.c
srcs/utils/get_escapestr.c
tests/utils/test_get_escapestr.c

`unset TE\ST`や`export TE\ST=100`等のコマンドでkeyがTESTとして認識されるようバックスラッシュをエスケープする関数を追加しました。
またMakefileを修正しテストコンパイル時にリリンクしないよう変更しています。

[add]バックスラッシュエスケープ追加、Makefile修正

---

Makefile
includes/minishell.h
srcs/expander/expand_tilde.c
srcs/expander/expander.c
srcs/expander/is_empty_env.c
tests/expander/test_expander.c

トークン中のクォートに囲まれていないチルダを環境変数HOMEで展開する関数を追加しました。
bashにxcオプションをつけて`echo ~`等を実行すると`~`がHOMEに展開されるためcdだけでなくすべてのコマンド実行前に`~`を展開するようにしました。

[add]チルダ展開追加

---

Makefile
includes/minishell.h
srcs/main/main.c
srcs/utils/update_shlvl.c

環境変数SHLVLの動作を再現する関数を追加しました。
SHLVLが999の時、新しいshellを起動するとSHLVLの値が1000にならない動作については、
reference等にも記載がないので再現していません。

[add]環境変数SHLVL追加

---

srcs/builtin/execute_export.c

exportコマンドにアンダースコアのみのkeyが入力されたとき、不適な値として処理するよう変更しました。

[fix]アンダースコアのみのkeyをエラーとするよう修正

---

srcs/utils/get_escapestr.c
tests/utils/test_get_escapestr.c

クォートの内外でバックスラッシュのエスケープが下記のように判定されるよう変更しました。
ダブルクォート中→　\一つはそのまま出力、\\\は\一つとして出力。
シングルクォート中→　すべてリテラルとして出力。
クォート外→　\一つはエスケープ、\\\は\一つとして出力。

[fix]get_escapestr修正

---

srcs/history/display_history.c
srcs/history/update_history.c
srcs/main/read_line.c

コピペ等で一度に複数文字入力されたときの動作を改善しました。
また、散らばっていた制御系文字を受け取った際の動作を一つの関数にまとめました。
validate_line修正時にheaderに宣言して名前が重複していた他のstatic関数の関数名を変更しました。

[fix]read_line修正、関数名変更

---

srcs/builtin/execute_exit.c

```
exit " 42 "
```
のようなケースを正常に見なすように修正しました。

exitの引数に標準空白文字類がある場合の対応

---

srcs/builtin/execute_cd.c
srcs/builtin/execute_pwd.c
srcs/execute/create_newpath.c
srcs/parser/parser_utils.c

・カレントディレクトリを削除後、cd ../など存在するディレクトリに移動した場合の対応
・set_pathで選択したpathが空文字の時、cdpathを失敗させるように修正
・pwdのパス出力にprintfを使用しないように変更
具体的に
```
mkdir dir; cd dir; rmdir ../dir; cd ./; pwd;cd .; pwd; cd ./././././; pwd; cd .////////./; pwd; cd ../; pwd
export CDPATH="/"; export HOME=; cd ; pwd
export CDPATH="../a"; mkdir -p a/b/c; cd b; pwd; cd a; pwd; cd b; pwd
```
のような対応しきれていなかったパターンに対応しました。

execute_cd仕上げ

---

srcs/builtin/execute_export.c
srcs/main/main.c
srcs/utils/print_sorted_env.c
srcs/utils/update_shlvl.c

```
export APPEND=1; export APPEND+=2; export | grep APPEND
export APPEND_NONE=1; export APPEND_NONE+=; export | grep APPEND_NONE
```
以上のような環境変数のvalueに文字列連結するパターンに対応しました。
update_shlvl内でgetenvしてくるSHLVL環境変数のvalueに含まれる標準空白文字類を取り除くようにしました。

[fix] export 文字列連結対応。update_shlvl修正

---

srcs/main/main.c
srcs/tokenizer/validate_quote.c

```
echo '
echo "
```
以上のようなパターンでセグフォが出ていたので、validate_quoteをvalidate_lineの前に呼び出すようにして解決しました。
また、クオートが閉じていない時のエラーメッセージをbashに合わせました。

[fix] クオートが閉じていない時のエラーメッセージ変更。validate_quoteとlineの実行順変更。

---

srcs/utils/update_shlvl.c

```
SPACES = "\v\r\f\t\n "
TRIMS = "\t\n "
VALUE = [SPACES]* [DIGITS] [TRIMS]*
```
valueが正常かどうかの判定を、以前はft_strtrimで標準空白文字類を取り除いてから行っていました。
今回の修正では、上のVALUEのパターンに当てはまるものを正常としました。
前にあるSPACESを飛ばし、ft_strtrimでTRIMSを除いたもの(DIGITS)が変数envに渡されます。

[fix] shlvlのvalueが正常かどうかの判定を修正

---

srcs/builtin/execute_cd.c
srcs/execute/create_newpath.c
srcs/utils/add_path.c
tests/execute/test_create_newpath.c

add_path_iterate(), set_cdpath_iterate()内からコールされるadd_pathで引数として受け取った変数pathをfreeするよう変更しました。
また、create_hierarchy()内で生成されるlistは引数dirを完全に包括しないのでlistのcontentはdupしたものを渡し、create_newpath()内でdirをフリーするように変更しました。
確認お願いします。

[fix]execute_cdメモリリーク修正

---

srcs/builtin/execute_unset.c
srcs/execute/start_commands.c

execute_unset()内でのget_escapestrを削除しました。
加えてstart_command()内で行っていたコマンドリストの開放を削除しています。（mainで解放しているため）

[fix]unset修正

---

Makefile
srcs/builtin/execute_export.c
srcs/utils/print_sorted_env.c
srcs/utils/sort_environ.c

exportの修正を忘れてしまっていて、遅くなりました。
上の修正の為、print_sorted_env.cの一部関数を、新ファイルsort_environ.cに分けました。

[fix] export 特殊文字のエスケープを文字列表示時のみにするよう修正

---

srcs/tokenizer/tokenize.c
srcs/tokenizer/validate_line.c
tests/tokenizer/test_validate_line.c

```echo hello ; >outfile ls```のようなセミコロン、パイプの直後に<>があるときエラーにならないよう修正しました。
```echo hello 1 > outfile```のようなコマンドで1と>が一つのトークンとして認識されていた問題を修正しました。

[fix]validate_line,tokenizer修正
